name:         evm-opcodes
version:      0.2.0
synopsis:     'Opcode types for Ethereum Virtual Machine (EVM)'
description:  'This library provides opcode types for the Ethereum Virtual Machine.'
category:     Ethereum, Finance, Network
license:      MIT
license-file: LICENSE
homepage:     https://github.com/sshine/evm-opcodes
author:       Simon Shine
maintainer:   simon@simonshine.dk
copyright:    2018-2024 Simon Shine
github:       sshine/evm-opcodes

extra-source-files:
  - README.md

dependencies:
  - base                        >= 4.12 && < 5
  - bytestring                  >= 0.10 && < 0.13
  - cereal                     ^>= 0.5
  - data-dword                 ^>= 0.3
  - containers                  >= 0.6 && < 0.8
  - text                        >= 1.2

library:
  exposed-modules:
    - EVM.Opcode
    - EVM.Opcode.Internal
    - EVM.Opcode.Positional
    - EVM.Opcode.Labelled
    - EVM.Opcode.Traversal
  source-dirs: src
  ghc-options:
    - -Wall
    - -Wnoncanonical-monad-instances
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints

tests:
  test:
    main: test.hs
    source-dirs: test
    dependencies:
      - evm-opcodes
      - tasty
      - tasty-discover
      - tasty-hspec
      - tasty-hedgehog
      - hedgehog
      - hspec

benchmarks:
  bench:
    main: bench.hs
    source-dirs: bench
    dependencies:
      - evm-opcodes
      - tasty-bench
    # ghc-options: -O2
